# Generated by Django 2.1 on 2018-08-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0002_auto_20180823_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexer',
            name='username',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
