# Generated by Django 2.1 on 2018-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0003_auto_20180823_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('bio', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('username', models.CharField(default='', max_length=10, unique=True)),
                ('token', models.CharField(default='', max_length=32, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Flexer',
        ),
    ]
