# Generated by Django 2.1 on 2018-08-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0004_auto_20180823_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='flexuser',
            name='friends',
            field=models.ManyToManyField(to='flexer.FlexUser'),
        ),
        migrations.AddField(
            model_name='flex',
            name='members',
            field=models.ManyToManyField(related_name='member', to='flexer.FlexUser'),
        ),
        migrations.AddField(
            model_name='flex',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flexer.FlexUser'),
        ),
    ]
