# Generated by Django 2.1 on 2018-08-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0005_auto_20180823_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flex',
            name='members',
            field=models.ManyToManyField(related_name='members', to='flexer.FlexUser'),
        ),
    ]
