# Generated by Django 2.1 on 2018-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0007_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexuser',
            name='friends',
            field=models.ManyToManyField(null=True, to='flexer.FlexUser'),
        ),
    ]
