# Generated by Django 2.1 on 2018-08-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0009_auto_20180823_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flex',
            options={'verbose_name': 'Flex', 'verbose_name_plural': 'Flexes'},
        ),
        migrations.AlterModelOptions(
            name='flexuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='flexuser',
            old_name='friends',
            new_name='subscribed',
        ),
    ]
