# Generated by Django 2.1 on 2018-08-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0010_auto_20180824_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
