# Generated by Django 2.1 on 2018-08-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0012_auto_20180824_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexuser',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
