# Generated by Django 2.1 on 2018-08-29 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0014_flex_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='flex',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
