# Generated by Django 2.1 on 2018-08-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0015_flex_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flex',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
