# Generated by Django 2.1 on 2018-09-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0017_auto_20180829_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flexuser',
            old_name='followed',
            new_name='friends',
        ),
    ]
