# Generated by Django 2.1 on 2018-11-16 20:47

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0021_auto_20181116_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexuser',
            name='fcm_registration_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flexuser',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=''),
        ),
    ]
