# Generated by Django 2.1 on 2018-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexer', '0022_auto_20181116_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexuser',
            name='fcm_registration_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
